CREATE DATABASE hospital_db;
USE hospital_db;

CREATE TABLE specialists (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    specialty VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    location ENUM('Yaounde', 'Douala', 'Buea', 'Bamenda', 'Limbe', 'North', 'Far North') NOT NULL,
    profile_image VARCHAR(255) NOT NULL -- Store image paths
);
INSERT INTO specialists (name, specialty, description, location, profile_image) VALUES
('Dr. John Doe', 'Cardiologist', 'Specialist in heart-related conditions like hypertension, heart attacks, and arrhythmias.', 'Yaounde', 'images/cardiologist.jpg'),
('Dr. Alice Smith', 'Neurologist', 'Expert in treating stroke, epilepsy, and nervous system disorders.', 'Douala', 'images/neurologist.jpg'),
('Dr. Mark Johnson', 'Orthopedic Surgeon', 'Specializes in treating fractures, joint replacements, and spinal surgeries.', 'Buea', 'images/orthopedic.jpg'),
('Dr. Emily Carter', 'Plastic Surgeon', 'Expert in cosmetic and reconstructive surgeries, including burn treatments.', 'Bamenda', 'images/plastic.jpg');
('Dr. John Doe', 'Cardiologist', 'Specialist in heart-related conditions like hypertension, heart attacks, and arrhythmias.', 'Yaounde', 'images/cardiologist.jpg'),
('Dr. Alice Smith', 'Neurologist', 'Expert in treating stroke, epilepsy, and nervous system disorders.', 'Douala', 'images/neurologist.jpg'),
('Dr. Mark Johnson', 'Orthopedic Surgeon', 'Specializes in treating fractures, joint replacements, and spinal surgeries.', 'Buea', 'images/orthopedic.jpg'),
('Dr. Emily Carter', 'Plastic Surgeon', 'Expert in cosmetic and reconstructive surgeries, including burn treatments.', 'Bamenda', 'images/plastic.jpg'),
('Dr. Henry Adams', 'Ophthalmologist', 'Diagnoses and treats eye diseases such as cataracts and glaucoma.', 'Limbe', 'images/ophthalmologist.jpg'),
('Dr. Olivia Brown', 'ENT Specialist', 'Manages ear, nose, and throat disorders, including sinus infections and hearing loss.', 'North', 'images/ent_specialist.jpg'),
('Dr. Nathan Wilson', 'Gastroenterologist', 'Specializes in digestive system diseases such as ulcers and liver diseases.', 'Far North', 'images/gastroenterologist.jpg'),
('Dr. Samuel Green', 'Pulmonologist', 'Focuses on lung conditions such as asthma, COPD, and tuberculosis.', 'Yaounde', 'images/pulmonologist.jpg'),
('Dr. Laura White', 'Nephrologist', 'Manages kidney-related diseases, including dialysis patients.', 'Douala', 'images/nephrologist.jpg'),
('Dr. Robert Lee', 'Hematologist', 'Diagnoses and treats blood disorders such as leukemia and anemia.', 'Buea', 'images/hematologist.jpg'),
('Dr. Julia Harris', 'Infectious Disease Specialist', 'Treats infections like HIV, tuberculosis, and hospital-acquired infections.', 'Bamenda', 'images/infectious_disease.jpg'),
('Dr. George Miller', 'Dermatologist', 'Treats skin, hair, and nail disorders like eczema and psoriasis.', 'Limbe', 'images/dermatologist.jpg'),
('Dr. Susan Turner', 'Allergist/Immunologist', 'Manages allergies, asthma, and immune system disorders.', 'North', 'images/allergist.jpg'),
('Dr. Christopher Evans', 'Oncologist', 'Specialist in the diagnosis and treatment of various cancers.', 'Far North', 'images/oncologist.jpg'),
('Dr. Patricia Thompson', 'Geriatrician', 'Focuses on medical care for elderly patients.', 'Yaounde', 'images/geriatrician.jpg'),
('Dr. Daniel Foster', 'Psychiatrist', 'Diagnoses and treats mental health disorders such as depression and schizophrenia.', 'Douala', 'images/psychiatrist.jpg'),
('Dr. Megan Scott', 'Psychologist', 'Provides therapy and counseling for mental health conditions.', 'Buea', 'images/psychologist.jpg'),
('Dr. Richard Walker', 'Radiologist', 'Interprets imaging tests like X-rays and MRIs.', 'Bamenda', 'images/radiologist.jpg'),
('Dr. Angela Robinson', 'Interventional Radiologist', 'Performs minimally invasive image-guided procedures like angioplasty.', 'Limbe', 'images/interventional_radiologist.jpg'),
('Dr. Steven King', 'Pathologist', 'Analyzes laboratory samples to diagnose diseases.', 'North', 'images/pathologist.jpg'),
('Dr. Heather Nelson', 'Nuclear Medicine Specialist', 'Uses radioactive materials for diagnosis and treatment.', 'Far North', 'images/nuclear_medicine.jpg'),
('Dr. Matthew Carter', 'Anesthesiologist', 'Administers anesthesia for surgeries and pain management.', 'Yaounde', 'images/anesthesiologist.jpg'),
('Dr. Rebecca Lopez', 'Pain Management Specialist', 'Treats chronic pain conditions such as fibromyalgia.', 'Douala', 'images/pain_management.jpg'),
('Dr. Brian Young', 'Physical Medicine & Rehabilitation', 'Helps patients recover from disabilities and injuries.', 'Buea', 'images/physiatrist.jpg'),
('Dr. Jennifer Hall', 'Physical Therapist', 'Improves mobility and function after injuries.', 'Bamenda', 'images/physical_therapist.jpg'),
('Dr. William Gonzalez', 'Occupational Therapist', 'Helps patients regain daily living skills.', 'Limbe', 'images/occupational_therapist.jpg'),
('Dr. Christine Martinez', 'Speech-Language Pathologist', 'Treats speech and communication disorders.', 'North', 'images/speech_pathologist.jpg'),
('Dr. Kevin Rodriguez', 'Urologist', 'Treats urinary system disorders and kidney stones.', 'Far North', 'images/urologist.jpg'),
('Dr. Melissa Perez', 'Andrologist', 'Specializes in male reproductive health.', 'Yaounde', 'images/andrologist.jpg'),
('Dr. Joshua Adams', 'Sexologist', 'Manages sexual health disorders.', 'Douala', 'images/sexologist.jpg'),
('Dr. Jessica Rivera', 'Geneticist', 'Diagnoses and manages inherited diseases.', 'Buea', 'images/geneticist.jpg'),
('Dr. Charles Collins', 'Palliative Care Specialist', 'Provides pain relief and end-of-life care.', 'Bamenda', 'images/palliative_care.jpg'),
('Dr. Amanda Carter', 'Toxicologist', 'Treats poisonings and chemical exposure cases.', 'Limbe', 'images/toxicologist.jpg'),
('Dr. Benjamin Baker', 'Transplant Surgeon', 'Performs organ transplants.', 'North', 'images/transplant_surgeon.jpg'),
('Dr. Katherine Scott', 'Bariatric Surgeon', 'Performs weight-loss surgeries.', 'Far North', 'images/bariatric_surgeon.jpg'),
('Dr. Paul Hughes', 'Aerospace Medicine Specialist', 'Deals with health effects of air travel.', 'Yaounde', 'images/aerospace_medicine.jpg'),
('Dr. Nancy Rogers', 'Forensic Pathologist', 'Conducts autopsies and determines causes of death.', 'Douala', 'images/forensic_pathologist.jpg'),
('Dr. Ethan Parker', 'Obstetrician & Gynecologist', 'Provides pregnancy care and reproductive health treatments.', 'Buea', 'images/obgyn.jpg'),
('Dr. Sophia Hernandez', 'Maternal-Fetal Medicine Specialist', 'Manages high-risk pregnancies.', 'Bamenda', 'images/maternal_fetal.jpg'),
('Dr. Ryan Wilson', 'Pediatrician', 'Provides medical care for children and adolescents.', 'Limbe', 'images/pediatrician.jpg'),
('Dr. Linda Sanchez', 'Neonatologist', 'Specializes in the care of premature newborns.', 'North', 'images/neonatologist.jpg'),
('Dr. Anthony Mitchell', 'Pediatric Surgeon', 'Performs surgeries on infants and children.', 'Far North', 'images/pediatric_surgeon.jpg'),
('Dr. Sarah Cooper', 'Emergency Medicine Physician', 'Treats urgent and life-threatening conditions in the ER.', 'Yaounde', 'images/emergency_medicine.jpg'),
('Dr. Brandon Phillips', 'Intensivist', 'Manages critically ill patients in the ICU.', 'Douala', 'images/intensivist.jpg'),
('Dr. Caroline Bennett', 'Trauma Surgeon', 'Specializes in treating severe injuries from accidents.', 'Buea', 'images/trauma_surgeon.jpg');